/**:
    ros__parameters:
        max_iteration: 8
        filter_size_surf: 0.3
        filter_size_map: 0.3
        cube_side_length: 5.0
        map_file_path: "./test.pcd"

        common:
            lid_topic:  "/sonar_point_cloud"
            imu_topic:  "/auv/imu/data_raw"
            time_sync_en: true
            time_offset_lidar_to_imu: 0.0

        preprocess:
            blind: 0.2

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree:    90.0
            det_range:     15.0
            extrinsic_est_en:  false
            extrinsic_T: [ 0.09382, -0.02148, 0.11593 ]
            extrinsic_R: [ 0.965925826, 0.0, 0.258819045,
                            0.0,         1.0, 0.0,
                            -0.258819045, 0.0, 0.965925826 ]

        publish:
            path_en:  false
            scan_publish_en:  true
            dense_publish_en: true
            scan_bodyframe_pub_en: true

        pcd_save:
            pcd_save_en: true
            interval: -1
