/**:
  ros__parameters:
    sonar:
      topic: /sonar_point_cloud
      frequency: 1.0
      extrinsic_T: [0.09382, 0.02148, 0.11593]
      extrinsic_R: [0.994521895, 0.0, 0.104528463, 0.0, 1.0, 0.0, -0.104528463, 0.0, 0.994521895]
      max_range: 15.0
      min_range: 0.2
      xy_covariance: 0.100002
      z_covariance: 0.160002
    imu:
      topic: /auv/imu/data_raw
      frequency: 100.0
      odometry_publish_frequency: 100.0
      initial_gravity_estimate: 9.806
      noiseless: false
      gyr_cov: 1.0e-06
      acc_cov: 0.1
      b_gyr_cov: 4.06e-05
      b_acc_cov: 0.12022
      init_b_gyr_cov: 0.0001
      init_b_acc_cov: 0.001
      init_gravity_covariance: 1.0e-05
      orientation_covariance: 3.0461742e-06
      accel_attitude_covariance: 0.0012184697
      accel_attitude_norm_gate: 2.0
      sonar_outage_timeout: 0.5
      sonar_return_ramp_time: 1.0
      unobservable_bias_covariance: 1.0e-10
    dvl:
      enable: true
      topic: /auv/dvl
      frequency: 15.0
      extrinsic_T: [-0.24219, 0.16095, -0.11538]
      extrinsic_R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
      covariance: 0.00057
      init_covariance: 6.04e-09
    pressure:
      enable: true
      topic: /auv/pressure/scaled2
      timeout: 0.25
      extrinsic_T: [-0.24219, -0.03954, 0.01898]
      fluid_density: 1025.6
      covariance: 40652.529
      init_covariance: 1.0e-06
    magnetometer:
      enable: true
      topic: /auv/imu/magnetic_field
      timeout: 0.25
      extrinsic_R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
      hard_iron_offset: [-4.8399958768e-07, -2.1439576902e-06, -6.5980944961e-06]
      soft_iron_matrix: [0.99935443753, -0.000517094627299, -0.00741214083726, -0.000517094627299, 1.01922807501, -0.00687066034456,
        -0.00741214083726, -0.00687066034456, 0.981870062061]
      mag_cov: 75.2
      heading_cov_floor: 0.00250075
    mapping:
      max_iteration: 8
      filter_size_surf: 0.3
      filter_size_map: 0.3
      cube_side_length: 100.0
      minimum_scan_points: 5
      minimum_effective_features: 1
      world_frame: World
      world_to_camera_init_T: [0.0, 0.0, 0.0]
      world_to_camera_init_R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
      map_file_path: ./test.pcd
      map_save_enable: true
    publish:
      corrected_map_enable: true
      corrected_map_topic: /uwfl2/corrected_map
    loop_closure:
      enable: false
      profile: balanced
