/**:
  ros__parameters:
    sonar:
      topic: /sonar_point_cloud
      frequency: 4.0
      translation: [0.09382, -0.02148, 0.11593]
      rotation: [0.0, 6.0, 0.0] # RPY degrees
      max_range: 15.0
      min_range: 0.2
      xy_covariance: 0.1
      z_covariance: 0.2
    imu:
      topic: /auv/imu/data_raw
      frequency: 200.0
      initial_gravity_estimate: 9.81
      gyroscope_covariance: 5.5e-06
      accelerometer_covariance: 0.1
      gyroscope_bias_covariance: 1.0e-06
      accelerometer_bias_covariance: 0.2
      init_gyroscope_bias_covariance: 0.0001
      init_accelerometer_bias_covariance: 0.001
      init_gravity_covariance: 1.0e-05
      orientation_covariance: 3.0461742e-06
      accel_attitude_covariance: 0.0012184697
      accel_attitude_norm_gate: 2.0
    dvl:
      enable: true
      topic: /auv/dvl
      frequency: 15.0
      translation: [-0.079, -0.09691, -0.25938]
      rotation: [0.0, 0.0, 0.0] # RPY degrees
      covariance: 0.0001
      init_covariance: 1.0e-08
    pressure:
      enable: true
      topic: /auv/pressure/scaled2
      frequency: 4.0
      translation: [-0.24219, -0.03954, 0.01898]
      fluid_density: 1025.0
      covariance: 40652.529
      init_covariance: 10000.0
    magnetometer:
      enable: true
      topic: /auv/imu/magnetic_field
      timeout: 0.25
      rotation: [0.0, 0.0, 0.0] # RPY degrees
      hard_iron_offset: [-0.3, -19.96, 86.7]
      soft_iron_matrix: [-1.257623, 0.0, 0.0, 0.0, -1.257623, 0.0, 0.0, 0.0, -1.0]
      covariance: 1.106168696543515
    mapping:
      max_iteration: 4
      filter_size_surf: 0.3
      filter_size_map: 0.3
      cube_side_length: 100.0
      world_frame: World
      world_initial_frame_translation: [-42.85783463854434, -61.44716108400654, -6.793090506770439]
      world_initial_frame_rotation: [0.980798775357985, -6.54814000113391, 117.986490532663] # RPY degrees
      map_file_path: ./test.pcd
    publish:
      corrected_map_enable: true
      corrected_map_topic: /uwfl2/corrected_map
    loop_closure:
      enable: false
      profile: balanced
